Require freesurfer license file as input.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -58,7 +58,6 @@ fi
 # Freesurfer License
 
 # User-Provided license file
-fs_file=''
 if [[ -d "$FREESURFER_LICENSE_DIR" ]]; then
   fs_file=$(find $FREESURFER_LICENSE_DIR/* -type f | head -1)
 fi
@@ -66,9 +65,8 @@ fi
 if [[ -n "$fs_file" ]]; then
   cp "$fs_file" ${LICENSE_FILE}
 else
-  touch ${LICENSE_FILE}
-  LICENSE=$(${FLYWHEEL_BASE}/parse_config.py --json_file=${CONFIG_FILE} -l)
-  echo -e ${LICENSE} > ${LICENSE_FILE}
+  echo -e "${CONTAINER}  A license file is required to run!"
+  exit 1
 fi
 
 
@@ -89,6 +87,7 @@ else
     exit 1
 fi
 
+# Show the contents of the BIDS directory
 ls -R ${BIDS_DIR}
 
 
